language: node_js
node_js:
  - "stable"
before_install:
  - npm i -g npm@6.6.0
install:
  - npm install
before_deploy:
  - npm run build
  - npm run export
deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $RP_BUCKET_NAME
    skip_cleanup: true
    local_dir: out
    on:
      branch: master
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $RP_BUCKET_NAME
    skip_cleanup: true
    local_dir: out
    on:
      branch: staging
after_deploy:
  - ./scripts/invalidate.sh
